// Generated by the Ballerina OpenAPI tool from specs/design/components/todo-api/openapi.yaml,
// then filled in by hand: the listener binds on all interfaces, the service is
// interceptable so the gateway assertion is verified on every request, and
// every resource resolves the caller through it and scopes rows to their own.

import ballerina/http;

listener http:Listener ep0 = new (9090);

service http:InterceptableService / on ep0 {

    public function createInterceptors() returns AssertionInterceptor => new;

    # The caller's todo items
    #
    # + return - returns can be any of following types
    # inline_response_200 (A page of the caller's todo items)
    # ErrorUnauthorized (Missing or invalid sign-in)
    resource function get me/todo\-items(http:RequestContext ctx, int 'limit = 20, int offset = 0)
            returns inline_response_200|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return unauthorizedError();
        }
        int effectiveLimit = 'limit > 100 ? 100 : ('limit < 0 ? 0 : 'limit);
        int effectiveOffset = offset < 0 ? 0 : offset;
        [TodoItemRecord[], int] page = check todoStore.list(caller.userId, effectiveLimit, effectiveOffset);
        TodoItemRecord[] records = page[0];
        int total = page[1];
        TodoItem[] data = from TodoItemRecord r in records
            select toApiItem(r);
        string? next = effectiveOffset + effectiveLimit < total
            ? pageLink(effectiveLimit, effectiveOffset + effectiveLimit) : ();
        string? previous = effectiveOffset > 0
            ? pageLink(effectiveLimit, previousOffset(effectiveOffset, effectiveLimit)) : ();
        return {count: total, next, previous, data};
    }

    # Create a todo item for the caller
    #
    # + return - returns can be any of following types
    # TodoItem (The created todo item)
    # ErrorBadRequest (Invalid todo item)
    # ErrorUnauthorized (Missing or invalid sign-in)
    resource function post me/todo\-items(http:RequestContext ctx, @http:Payload TodoItemInput payload)
            returns TodoItem|ErrorBadRequest|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return unauthorizedError();
        }
        string title = payload.title.trim();
        if title == "" {
            return badRequestError("title is required");
        }
        string? dueDate = payload?.dueDate;
        TodoItemRecord created = check todoStore.create(caller.userId, title, dueDate);
        return toApiItem(created);
    }

    # The caller's single todo item
    #
    # + return - returns can be any of following types
    # TodoItem (The todo item)
    # ErrorUnauthorized (Missing or invalid sign-in)
    # ErrorNotFound (No such todo item for this caller)
    resource function get me/todo\-items/[string itemId](http:RequestContext ctx)
            returns TodoItem|ErrorUnauthorized|ErrorNotFound|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return unauthorizedError();
        }
        TodoItemRecord? item = check todoStore.get(caller.userId, itemId);
        if item is () {
            return notFoundError();
        }
        return toApiItem(item);
    }

    # Update the caller's todo item (title, due date, done)
    #
    # + return - returns can be any of following types
    # TodoItem (The updated todo item)
    # ErrorBadRequest (Invalid update)
    # ErrorUnauthorized (Missing or invalid sign-in)
    # ErrorNotFound (No such todo item for this caller)
    resource function patch me/todo\-items/[string itemId](http:RequestContext ctx, @http:Payload TodoItemUpdate payload)
            returns TodoItem|ErrorBadRequest|ErrorUnauthorized|ErrorNotFound|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return unauthorizedError();
        }
        map<json> payloadJson = <map<json>>payload.toJson();
        TodoUpdateFields fields = {};
        if payloadJson.hasKey("title") {
            string title = payload?.title ?: "";
            string trimmed = title.trim();
            if trimmed == "" {
                return badRequestError("title must not be empty");
            }
            fields.title = trimmed;
            fields.titleProvided = true;
        }
        if payloadJson.hasKey("dueDate") {
            fields.dueDate = payload?.dueDate;
            fields.dueDateProvided = true;
        }
        if payloadJson.hasKey("done") {
            fields.done = payload?.done;
            fields.doneProvided = true;
        }
        TodoItemRecord? updated = check todoStore.update(caller.userId, itemId, fields);
        if updated is () {
            return notFoundError();
        }
        return toApiItem(updated);
    }

    # Delete the caller's todo item
    #
    # + return - returns can be any of following types
    # http:NoContent (Deleted)
    # http:Unauthorized (Missing or invalid sign-in)
    # http:NotFound (No such todo item for this caller)
    resource function delete me/todo\-items/[string itemId](http:RequestContext ctx)
            returns http:NoContent|ErrorUnauthorized|ErrorNotFound|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller is http:Unauthorized {
            return unauthorizedError();
        }
        boolean deleted = check todoStore.delete(caller.userId, itemId);
        if !deleted {
            return notFoundError();
        }
        return http:NO_CONTENT;
    }
}

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type TodoItem record {
    string id;
    string title;
    boolean done;
    string? dueDate?;
    string createdAt;
    string updatedAt;
};

public type TodoItemUpdate record {
    string title?;
    string? dueDate?;
    boolean done?;
};

public type inline_response_200 record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    TodoItem[] data;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type TodoItemInput record {
    string title;
    string? dueDate?;
};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
